### ISSUE TITLE
Investigate slowdown in blogpost

### ISSUE THREAD

**Issue by pdeffebach** [JuliaData/DataFramesMeta.jl#244] opened 2021-04-22 02:21 UTC
[Here](http://dm13450.github.io/2021/04/21/Accidentally-Quadratic.html) is a blog post showing a slow-down due to DataFramesMeta. 

Better investigate why it's slow.

**Comment by bkamins** [comment] 2021-04-22 07:20
I do not think there is a slow-down. The operation was also slow in the past IMO. Can you reproduce the slowdown? The issue is that `findall` transforms the lookup table into `Set`, while `@where` is not able to do so.

**Comment by bkamins** [comment] 2021-04-22 07:27
`@where(df, in(Set(ids)).(:B))` should normally be used for such a look-up as requested in the blog post and this is fast.
The trick is that `findall` is able to do this operation (transform `ids` to `Set(ids)`) "under the hood",
while if you use broadcasting you need to convert `ids` to `Set(ids)` manually.
AFAICT it is just how Julia Base works and has no relationship with DataFramesMeta.jl.

CC dm13450

**Comment by nalimilan** [comment] 2021-05-02 14:49
Maybe this could be fixed in Base by using the same tricks with broadcasting `Base.Fix2{typeof(in)}` as with `findall`.

**Comment by bkamins** [comment] 2021-05-02 15:08
Yes - this should be fixed in Base.

**Closed** 2021-05-16 15:00 UTC
